/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import connection.DatabaseTanding;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class TeamBeranda extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form TeamBeranda
     */
    private String id_team;
    private String id_teamSearch;
    private String id_fieldSearch;
    public TeamBeranda() {
        initComponents();
        conn = DatabaseTanding.getConnection();
        btn_visitTeam.setVisible(false);
        btn_visitField.setVisible(false);
    }
    public TeamBeranda(String id){
        initComponents();
        conn = DatabaseTanding.getConnection();
        id_team = id;
        btn_visitTeam.setVisible(false);
        btn_visitField.setVisible(false);
        readDataTeam();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_teamProfile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dst_teamPhoto = new javax.swing.JDesktopPane();
        imageLabel = new javax.swing.JLabel();
        label_teamName = new javax.swing.JLabel();
        label_teamPhone = new javax.swing.JLabel();
        label_teamDomisili = new javax.swing.JLabel();
        pnl_teamSearch = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_teamSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_teamSearch = new javax.swing.JTable();
        btn_visitTeam = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_fieldSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_fieldSearch = new javax.swing.JTable();
        btn_visitField = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl_teamProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("TEAM PROFILE");

        dst_teamPhoto.setLayer(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dst_teamPhotoLayout = new javax.swing.GroupLayout(dst_teamPhoto);
        dst_teamPhoto.setLayout(dst_teamPhotoLayout);
        dst_teamPhotoLayout.setHorizontalGroup(
            dst_teamPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        dst_teamPhotoLayout.setVerticalGroup(
            dst_teamPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        label_teamName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_teamName.setText("Team Name");

        label_teamPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_teamPhone.setText("Contact Number");

        label_teamDomisili.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_teamDomisili.setText("Domisili");

        javax.swing.GroupLayout pnl_teamProfileLayout = new javax.swing.GroupLayout(pnl_teamProfile);
        pnl_teamProfile.setLayout(pnl_teamProfileLayout);
        pnl_teamProfileLayout.setHorizontalGroup(
            pnl_teamProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_teamProfileLayout.createSequentialGroup()
                .addGroup(pnl_teamProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_teamProfileLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnl_teamProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_teamName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_teamPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_teamDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dst_teamPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_teamProfileLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnl_teamProfileLayout.setVerticalGroup(
            pnl_teamProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_teamProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dst_teamPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(label_teamName)
                .addGap(18, 18, 18)
                .addComponent(label_teamPhone)
                .addGap(18, 18, 18)
                .addComponent(label_teamDomisili)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnl_teamSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txt_teamSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_teamSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_teamSearchKeyReleased(evt);
            }
        });

        tb_teamSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_teamSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_teamSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_teamSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_teamSearch);

        btn_visitTeam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_visitTeam.setText("VISIT TEAM");
        btn_visitTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_visitTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_teamSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_visitTeam)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_teamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_visitTeam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Team", jPanel1);

        txt_fieldSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_fieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fieldSearchKeyReleased(evt);
            }
        });

        tb_fieldSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_fieldSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_fieldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_fieldSearchMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_fieldSearch);

        btn_visitField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_visitField.setText("CHECK FIELD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fieldSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_visitField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_visitField)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Search Field", jPanel2);

        javax.swing.GroupLayout pnl_teamSearchLayout = new javax.swing.GroupLayout(pnl_teamSearch);
        pnl_teamSearch.setLayout(pnl_teamSearchLayout);
        pnl_teamSearchLayout.setHorizontalGroup(
            pnl_teamSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        pnl_teamSearchLayout.setVerticalGroup(
            pnl_teamSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_teamSearchLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(433, 433, 433))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnl_teamProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(pnl_teamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_teamProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_teamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_teamSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_teamSearchKeyReleased
        // TODO add your handling code here:
        String paramName = "'%"+txt_teamSearch.getText()+"%'";
        String sql = "select id_team, teamname,contact,region from team where teamname like" + paramName;
            
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb_teamSearch.setModel(DbUtils.resultSetToTableModel(rs));              
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_teamSearchKeyReleased

    private void txt_fieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fieldSearchKeyReleased
        // TODO add your handling code here:
        String paramName = "'%"+txt_teamSearch.getText()+"%'";
        String sql = "select id_team, teamname,contact,region from team where teamname like" + paramName;
            
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb_teamSearch.setModel(DbUtils.resultSetToTableModel(rs));              
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_fieldSearchKeyReleased

    private void tb_teamSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_teamSearchMouseClicked
        // TODO add your handling code here:
        int row = tb_teamSearch.getSelectedRow();
        String idteamClickTable = (tb_teamSearch.getModel().getValueAt(row,0).toString());
        
        try{
            String sql = "select * from team where id_team = '"+idteamClickTable+"' ";
            pst = conn.prepareStatement(sql);            
            rs = pst.executeQuery();
            
            
            //Set Inputan dengan yang diklik ditable
            if(rs.next()){
                id_teamSearch = rs.getString("id_team");
                btn_visitTeam.setVisible(true);
            }
                    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_tb_teamSearchMouseClicked

    private void btn_visitTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_visitTeamActionPerformed
        // TODO add your handling code here:
//        new VisitTeam(id_teamSearch).setVisible(true);
    }//GEN-LAST:event_btn_visitTeamActionPerformed

    private void tb_fieldSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_fieldSearchMouseClicked
        // TODO add your handling code here:
        int row = tb_fieldSearch.getSelectedRow();
        String idfieldClickTable = (tb_fieldSearch.getModel().getValueAt(row,0).toString());
        
        try{
            String sql = "select * from fieldowner where id_field = '"+idfieldClickTable+"' ";
            pst = conn.prepareStatement(sql);            
            rs = pst.executeQuery();
            
            
            //Set Inputan dengan yang diklik ditable
            if(rs.next()){
                id_teamSearch = rs.getString("id_field");
                btn_visitField.setVisible(true);
            }
                    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_tb_fieldSearchMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
//            tb_search.setModel(new DefaultTableModel());
            String sql = "select * from team WHERE id_team = '"+id_team+"'";
            pst = conn.prepareStatement(sql);
                      
            rs = pst.executeQuery();
            if(rs.next()){
                String teamName = rs.getString("teamname");
                String contactNo = rs.getString("contact");
                String domisili = rs.getString("region");
                label_teamName.setText(teamName);
                label_teamPhone.setText(contactNo);
                label_teamDomisili.setText(domisili);
                
                
                byte[] imagedata = rs.getBytes("photo");
                viewimage = new ImageIcon(imagedata);
                imageLabel.setIcon(viewimage);
            }else{
                JOptionPane.showMessageDialog(null, "Team Name didn't show");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error : "+ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened
    
    public void readDataTeam(){
        try{
            String sql = "select * from team";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb_teamSearch.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    public void readDataField(){
        try{
            String sql = "select * from fieldowner";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tb_fieldSearch.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamBeranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_visitField;
    private javax.swing.JButton btn_visitTeam;
    private javax.swing.JDesktopPane dst_teamPhoto;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_teamDomisili;
    private javax.swing.JLabel label_teamName;
    private javax.swing.JLabel label_teamPhone;
    private javax.swing.JPanel pnl_teamProfile;
    private javax.swing.JPanel pnl_teamSearch;
    private javax.swing.JTable tb_fieldSearch;
    private javax.swing.JTable tb_teamSearch;
    private javax.swing.JTextField txt_fieldSearch;
    private javax.swing.JTextField txt_teamSearch;
    // End of variables declaration//GEN-END:variables
    private ImageIcon viewimage = null;
}
